"""CQE Pipeline Types

@module quro.pipeline.cqe.types
@intent Data structures for CQE pipeline (detox, MI, invariants, stability)
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass(frozen=True)
class GraphEntropyMetrics:
    """Metrics to measure graph structural entropy.

    Used to detect semantic drift and structural pollution.
    """
    avg_out_degree: float
    hub_ratio: float
    weight_variance: float
    entropy_score: float


@dataclass(frozen=True)
class GraphManifest:
    """Metadata for a specific version of the graph index.

    Ensures that the graph being queried or detoxed matches
    the current environment/branch.
    """
    commit_hash: str
    branch: str
    timestamp: float
    symbol_count: int


@dataclass(frozen=True)
class FixPlanAction:
    """Deterministic action for the Indexer to fix graph issues.

    Action types:
    - downweight_edges: Reduce edge weights from god nodes
    - merge_alias: Merge similar symbols into canonical form
    - adjust_weight: Fix weight inflation (weight > 1.0)
    """
    action_type: str
    target: str
    details: Dict


@dataclass
class DetoxReport:
    """Diagnostic report generated by the Graph Detox Scanner.

    Contains:
    - manifest: Graph version metadata
    - entropy: Structural entropy metrics
    - manifest_errors: Version mismatch issues
    - god_nodes: Nodes with excessive out-degree
    - alias_conflicts: Similar symbols causing ambiguity
    - decay_warnings: Weight inflation issues
    - fix_plan: Actionable fixes for detected issues
    """
    manifest: Optional[GraphManifest] = None
    entropy: Optional[GraphEntropyMetrics] = None
    manifest_errors: List[Dict] = field(default_factory=list)
    god_nodes: List[Dict] = field(default_factory=list)
    alias_conflicts: List[Dict] = field(default_factory=list)
    decay_warnings: List[Dict] = field(default_factory=list)
    fix_plan: List[FixPlanAction] = field(default_factory=list)

    def is_healthy(self) -> bool:
        """Check if graph is healthy (no critical issues)."""
        if self.manifest_errors or self.god_nodes or self.alias_conflicts or self.decay_warnings:
            return False
        if self.entropy and (self.entropy.avg_out_degree > 30 or self.entropy.hub_ratio > 0.02):
            return False
        return True
